# Generated by Django 4.2 on 2023-06-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ahci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AhciCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AhciJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=9)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Erih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=9)),
                ('title', models.CharField(max_length=250)),
                ('discipline', models.CharField(max_length=200)),
                ('cat_2007', models.CharField(max_length=4, null=True)),
                ('cat_2011', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JcrCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JcrJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=9, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JcrScoreMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=4)),
                ('year', models.PositiveSmallIntegerField()),
                ('ais', models.FloatField()),
                ('quartile', models.PositiveSmallIntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.jcrcategory')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.jcrjournal')),
            ],
        ),
        migrations.CreateModel(
            name='JcrScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('ais', models.FloatField(null=True)),
                ('ris', models.FloatField(null=True)),
                ('rif', models.FloatField(null=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.jcrjournal')),
            ],
        ),
        migrations.CreateModel(
            name='JcrGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3)),
                ('year', models.PositiveSmallIntegerField()),
                ('index', models.CharField(max_length=4)),
                ('zone', models.PositiveSmallIntegerField()),
                ('top', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.jcrcategory')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.jcrjournal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='erih',
            constraint=models.CheckConstraint(check=models.Q(('discipline__in', ['Anthropology', 'Archaeology', 'Art and Art History', 'Classical Studies', 'Gender Studies', 'History', 'History & Philosophy of Science', 'Linguistics', 'Literature', 'Musicology', 'Oriental and African studies', 'Pedagogical & Educational Research', 'Philosophy', 'Psychology', 'Religious Studies and Theology'])), name='confirm_discipline'),
        ),
        migrations.AddField(
            model_name='ahcijournal',
            name='category',
            field=models.ManyToManyField(through='table.Ahci', to='table.ahcicategory'),
        ),
        migrations.AddField(
            model_name='ahci',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.ahcicategory'),
        ),
        migrations.AddField(
            model_name='ahci',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.ahcijournal'),
        ),
        migrations.AddConstraint(
            model_name='jcrscoremore',
            constraint=models.CheckConstraint(check=models.Q(('index__in', ['SCIE', 'SSCI'])), name='confirm_index_cifre'),
        ),
        migrations.AddConstraint(
            model_name='jcrgroup',
            constraint=models.CheckConstraint(check=models.Q(('index__in', ['SCIE', 'SSCI'])), name='confirm_index_grupe'),
        ),
        migrations.AddConstraint(
            model_name='jcrgroup',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['ais', 'if'])), name='confirm_type'),
        ),
    ]
